<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bullseye" Version="6.3.0" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
    <PackageVersion Include="SimpleExec" Version="13.1.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.35.0.4138" />
  </ItemGroup>
</Project>
